api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: "@AppBundle/Resources/config/routing.yml"
home:
    path: /
    defaults: { _controller: AppBundle:Default:index }
